language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

script: py.test  --cov-report term --cov=main

env:
  - CODECOV_TOKEN=8a295a11-1eba-427b-b894-a32758fb2804

after-success:
  - codecov
